[database]
host = LOCALHOST
#port = 3060
port = 3050
database = C:\Memoria\SisComInd\Dados\CONSTRUMIL.FDB
user = SYSDBA
#password = Mil2156
password = masterkey
pageSize = 4096

[API]
url = http://192.168.0.71:3000